"""Prompt contract for AI message classification."""

from __future__ import annotations

from triak_trade.ai.schemas import AIMessageContext


def build_telegram_signal_prompt(context: AIMessageContext) -> str:
    """Build strict JSON-only prompt for AI classification."""
    return (
        "You are a Telegram trading-signal classifier. "
        "Classify message with channel context and return JSON only. "
        "Never return markdown, prose, or code fences. "
        "Use exactly these classification enum values: "
        "NEW_SIGNAL, SIGNAL_UPDATE, CANCEL, CLOSE, RESULT_REPORT, "
        "ADVERTISEMENT, GENERAL_ANALYSIS, UNRELATED, AMBIGUOUS, UNKNOWN. "
        "Use exactly these action values where applicable: "
        "open, cancel, close, update_sl, update_tp, update_leverage, update_entry, "
        "ignore, unknown. "
        "Categories: new signal, signal update, cancellation, close instruction, "
        "TP/SL update, leverage update, result/profit report, advertisement, unrelated, ambiguous. "
        "Required JSON keys: classification, action, market, symbol, symbol_raw, side, "
        "entry_type, entry_low, entry_high, entry_prices, stop_loss, take_profits, "
        "leverage, leverage_mode, close_fraction, move_stop_to_entry, related_signal_id, "
        "relation_reason, source_message_ids, extracted_from_context, missing_fields, "
        "confidence, reasoning_summary, risk_notes, ignored_numeric_tokens, "
        "requires_admin_confirmation, raw_provider_metadata. "
        "All price-like numeric fields must be strings in the JSON output, not numbers. "
        "Extract structured fields only. Do not invent missing SL/TP/entry values. "
        "If unsure use AMBIGUOUS. "
        "Do not treat profit reports like TP hit, SL hit, +120% profit as new signals. "
        "Never extract prices, targets, stop-loss, leverage, or entry values from URLs, "
        "Telegram links, message IDs, emoji counters, numbering tokens like 1/2/3/4, "
        "or decorative labels. Put rejected numeric tokens into ignored_numeric_tokens. "
        "Use reply-chain context and up to the next 3 following messages when they look like "
        "continuations of the same signal. "
        "Messages may split symbol/side, targets, and stop-loss across separate posts. "
        "If a reply updates, cancels, closes, or changes stop-loss/take-profit/leverage "
        "for a previous signal, classify it as a related update, cancel, or close "
        "instead of a new signal. "
        "If the message is a caption or includes image context, use the image "
        "together with the text. "
        "Do not execute trades. Do not provide private chain-of-thought. "
        "Provide only short reasoning_summary. "
        "Logic must generalize across channels. "
        "Tofan_Trade is only a future test target, never a hard-coded rule. "
        "If values were recovered from reply/following context, set extracted_from_context=true "
        "and include all contributing message IDs in source_message_ids. "
        f"Context channel_id={context.channel_id}, message_id={context.message_id}, "
        f"message_has_media={context.message_has_media}, "
        f"message_is_caption={context.message_is_caption}."
    )
